### ISSUE TITLE
Warn the user when WebGL is disabled

### ISSUE THREAD

**Issue by Elfahor** [EepyBerry/lagrange#4]
If WebGL is disabled in the user's browser, they are just stuck facing a black screen. It would be nice to add a popup or some sort of warning so that they know what the problem is. Perhaps with a link to documentation explaining how to fix the issue in their browser?

**Comment by EepyBerry** [comment]
Good idea, I'll add this in the next version (0.3)!
Thanks <3

**Comment by EepyBerry** [comment]
Implemented in current dev branch :)
